# Generated by Django 3.1.1 on 2020-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='instance',
            field=models.TextField(default=''),
        ),
    ]
