# Generated by Django 3.1.1 on 2020-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_games_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='instance',
            field=models.TextField(default='{}'),
        ),
    ]
